#!/usr/bin/env ruby

require_relative 'lib/solanum'

# Hardware sensor data.
$sensors = run "sensors" do
  match /^Core 0:\s+\+(\d+\.\d+)°C/, record: "sensor coretemp", cast: :to_f
  match /^temp1:\s+\+(\d+\.\d+)°C/,  record: "sensor temp1",    cast: :to_f
  match /^temp2:\s+\+(\d+\.\d+)°C/,  record: "sensor temp2",    cast: :to_f
  match /^temp3:\s+\+(\d+\.\d+)°C/,  record: "sensor temp3",    cast: :to_f
end

##### REPORT LOOP #####

require 'riemann/client'

$riemann = Riemann::Client.new

loop do
  metrics = Solanum.collect($sensors)
  metrics.each do |metric, value|
    puts "%-40s %5d" % [metric, value]
    $riemann << {service: metric, metric: value, state: "ok", ttl: 10}
  end
  sleep 5
end
