" ~/.vimrc
" Place local overrides in ~/.vim/plugin/local.vim


" ----- GENERAL SETTINGS -----

set nocompatible          " use vim defaults
set encoding=utf-8
set modeline              " allow modelines
set modelines=20          " check the first 20 lines in a file
set ttyfast

" allow backspacing over everything
set backspace=indent,eol,start
map!  <BS>

" store files under ~/.vim/tmp/
set directory=~/.vim/tmp/
set backupdir=~/.vim/tmp/
"set undodir=~/.vim/tmp
"set undofile
set nobackup


" Load Vundle if present.
if filereadable($HOME . "/.vim/vundle.vim")
    source $HOME/.vim/vundle.vim
endif



" ----- APPEARANCE -----

" enable syntax highlighting
syntax on

" some general settings
"set cursorline
set laststatus=2
set number
set ruler
set showmatch
set showmode
set showcmd
"set visualbell

" do not wrap lines
set nowrap
set textwidth=0

" scroll when the cursor is within 5 lines of the edge of the window
set scrolloff=5
set sidescroll=10

" use rational split locations for new windows
set splitbelow
set splitright

" when comparing files, keep them synced and ignore whitespace
set diffopt=filler,iwhite

" configure code folding
"set foldcolumn=2          " set a column incase we need it
"set foldlevel=0           " show contents of all folds
"set foldmethod=indent     " use indent unless overridden



" ----- INDENTATION -----

" autoindent new lines
set autoindent

" indent with four-space tabs by default
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" display full-width tabs when using list
set listchars=trail:~
set listchars+=tab:>-
"execute 'set listchars+=tab:' . nr2char(187) . nr2char(183)
set list



" ----- SEARCHING -----

" use perl regexes
"nnoremap / /\v
"vnoremap / /\v

" make all-lower-case searches case-insensitive
set ignorecase
set smartcase

" search defaults
set gdefault
set incsearch
set hlsearch



" ----- SHORTCUTS -----

" use comma as the leader key
let mapleader = ","

" quick shortcut to clear search highlights
nnoremap <leader><space> :noh<cr>

" convert tabs to spaces
nnoremap <leader>t :%s/\t/  /<cr>
nnoremap <leader>T :%s/\t/    /<cr>

" strip trailing whitespace from the file
nnoremap <leader>s :%s/\s\+$//<cr>
" add this to unhighlight things: :let @/=''<cr>

" select text which was just pasted
nnoremap <leader>v V`]

" reverse the highlighted lines
command! -bar -range=% Reverse <line1>,<line2>g/^/m<line1>-1|nohl
vnoremap <leader>r :Reverse<cr>

" find diff merge lines
nnoremap <leader>m /[<=>]\{7}<cr>

" insert disapproval
nnoremap <leader>d A ಠ_ಠ<esc>

" use tab to jump to matching enclosure pairs
nnoremap <tab> %
vnoremap <tab> %



" ----- AUTOCOMPLETION -----

" allow autocompletion for commands and menus
set wildmode=longest,list,full
set wildmenu

" ignore VCS directories
set wildignore+=.git,.svn

" suffixes that get lower priority when doing tab completion for filenames
set suffixes=~,.bak,.swp,.o,.so,.ko,.class,.log



" ----- FILETYPE SETTINGS -----

filetype plugin indent on

" disable syntax error highlighting of C++ keywords in Java files
let java_allow_cpp_keywords = 1
