# Desktop wallpaper config

#splash = false

wallpaper {
    monitor = DP-3
    path = $HOME/.local/state/wallpaperctl/current.DP-3
}

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/.local/state/wallpaperctl/current.HDMI-A-1
}
