#!/bin/sh

##### Configuration #####

synergy_addr="127.0.0.1"
synergy_port=24800
synergy_dir="util/synergy"

client_name="laptop"
client_log="synergyc.log"

server_name="desktop"
server_host="greglook-1.desktop.amazon.com"



##### Connection #####

ssh_opts="-nf -L ${synergy_port}:${synergy_addr}:${synergy_port} ${server_host}"

if [[ -n $(ps aux | grep synergyc | grep -v grep) ]]; then
    echo "Killing running Synergy client..."
    killall synergyc
fi

if [[ -n $(ps aux | egrep "ssh ${ssh_opts}" | grep -v grep) ]]; then
    echo "Killing extant Synergy connections..."
    ps auxwww | grep "ssh ${ssh_opts}" | awk '{print $2}' | xargs kill
fi

echo "Connecting to remote host..."
ssh ${ssh_opts} "cd ~/${synergy_dir} && ./start-server"
sleep 5

echo "Starting Synergy client..."
synergyc -f --debug DEBUG --name ${client_name} ${synergy_addr}:${synergy_port} > $HOME/${synergy_dir}/${client_log} 2>&1 &
