#!/bin/sh

# change to synergy directory
#cd $(dirname $(readlink -f $0))

# kill any old servers
if [[ -n $(ps aux | grep synergys | grep -v grep) ]]; then
    echo "Killing old detached server..."
    killall synergys
    sleep 3
fi

echo "Starting Synergy server..."
synergys -f --config synergy.conf --name desktop --debug NOTE > synergys.log 2>&1
